toolbox:
  enabled: true

configOverride: |
  [global]
  osd_pool_default_pg_num = 8
  osd_pool_default_pgp_num = 8

cephClusterSpec:
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    count: 2
  storage:
    useAllNodes: false
    useAllDevices: false

    nodes:
      - name: "deb2"
        devices:
          - name: "sdb"
      - name: "deb3" 
        devices:
          - name: "sdb"
      - name: "deb4"
        devices:
          - name: "sdb"

cephBlockPools:
  - name: ceph-blockpool
    spec:
      failureDomain: host
      replicated:
        size: 3